title: Seminar ICFD
url: "https://heinten.github.io"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
nav_external_links_new_tab: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
math: mathjax