theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
nav_pages:
  - 1_command_line/command_line.md